# Generated by Django 3.2.8 on 2021-10-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/Donor/default.png', null=True, upload_to='profile_pic/Donor/'),
        ),
    ]
