# Generated by Django 3.2.8 on 2021-10-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_doctorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/Donor/default.png', null=True, upload_to='profile_pic/Patient/'),
        ),
    ]
