# Generated by Django 3.2.8 on 2021-10-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequestanyone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequestanyone',
            name='donor',
        ),
        migrations.AddField(
            model_name='bloodrequestanyone',
            name='donor_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bloodrequestanyone',
            name='donor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequestanyone',
            name='patient_mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
